---
title: "dp_analysis"
author: "Nathaniel Imel"
date: "2024-02-09"
output: html_document
---

```{r setup}
library(tidyverse)
library(lme4)
library(modelr)
library(viridis)
library(ggrepel)
library(latex2exp)
library(broom.mixed)
library(jtools)
```


```{r load}
df_se_imp <- read_csv("/Users/nathanielimel/uw/projects/modals-effcomm/outputs/universe=experiment_prohibition/prior=semi_estimated/utility=importance/agent_type=literal/analysis/all_data.csv") %>% mutate(
  prior = "semi_estimated",
  utility = "importance",
)

df_se_flat <- read_csv("/Users/nathanielimel/uw/projects/modals-effcomm/outputs/universe=experiment_prohibition/prior=semi_estimated/utility=half_credit/agent_type=literal/analysis/all_data.csv") %>% mutate(
  prior = "semi_estimated",
  utility = "half_credit",
)

df_uniform_imp <- read_csv("/Users/nathanielimel/uw/projects/modals-effcomm/outputs/universe=experiment_prohibition/prior=1e-20/utility=importance/agent_type=literal/analysis/all_data.csv") %>% mutate(
  prior = "uniform",
  utility = "importance",
)


df_uniform_flat <- read_csv("/Users/nathanielimel/uw/projects/modals-effcomm/outputs/universe=experiment_prohibition/prior=1e-20/utility=half_credit/agent_type=literal/analysis/all_data.csv") %>% mutate(
  prior = "uniform",
  utility = "half_credit",
)

# R sucks
df_all <- rbind( rbind( rbind(df_se_imp, df_se_flat), df_uniform_imp), df_uniform_flat)
df_all
```


```{r regression}

# Regression
getregr <- function(y, prior_name, util_name) {
  
  df_regr <- df_all %>% filter(
    prior == prior_name,
    utility == util_name,
  ) %>% mutate(
    optimality_z = scale(optimality),
    informativity_z = scale(informativity),
)
  
    
  # fit reduced models
  model_natural <- lmer(informativity ~ natural + (1 | original_name), data = df_regr)
  # model_natural <- lm(optimality ~ natural, data = df_s)
  
  model_dp <- lmer(informativity ~ dp_medium + (1 | original_name), data = df_regr)
  # model_dp <- lm(optimality ~ dp_medium, data = df_s)  

  return(model_dp)
    
}


```


```{r coefficients}

for (prior_name in c("uniform", "semi_estimated")) {
  for (util_name in c("half_credit", "importance")) {
    (
     plot_summs(
        getregr(prior_name, util_name),
        # colors = "Rainbow",
        point.shape = FALSE,
        # robust=TRUE,
        inner_ci_level = .9
        # plot.distributions = TRUE
      )
      + theme(
        axis.text.x = element_text(size=24),
        axis.text.y = element_blank()
      )
  
    )
  }
}

```