---
title: "dp_regr"
author: "Nathaniel Imel"
date: "2024-02-12"
output: html_document
---

```{r setup}
library(tidyverse)
library(lme4)
library(modelr)
library(car)
library(lmtest)
```


```{r load}
df = read_csv("df_regr.csv")
head(df)
```


```{r scale}

df_s <- df %>% 
  mutate(
    optimality_z = scale(optimality),
  )
```

```{r model0}

# Predict (unscaled for now, so range [0,1]) optimality from
# - natural (bool)
# - dp_medium (bool)
# - no interaction, because no case where natural=1 and dp=0

model0 <- lm(optimality ~ natural + dp_medium, df_s)
summary(model0)
```


```{r model1}

# Predict (unscaled for now, so range [0,1]) optimality from
# - natural (bool)
# - dp_medium (bool)
# - random intercepts for original_name (shared name of natural and derived variants)
# - no interaction, because no case where natural=1 and dp=0

model1 <- lmer(optimality ~ natural + dp_medium + (1 | original_name), df_s)
print(summary(model1))
print(anova(model1))
print(Anova(model1))
```


```{r model2}

# Predict scaled optimality from
# - natural (bool)
# - dp_medium (bool)
# - random intercepts for original_name (shared name of natural and derived variants)
# - no interaction, because no case where natural=1 and dp=0

model2 <- lmer(optimality_z ~ natural + dp_medium + (1 | original_name), df_s)
print(summary(model2))
print(anova(model2))
print(Anova(model2))
```


```{r lr}

#fit full model
model_full <- lm(optimality ~ natural + dp_medium, data = df_s)

#fit reduced models
model_natural <- lm(optimality ~ natural, data = df_s)
model_dp <- lm(optimality ~ dp_medium, data = df_s)

#perform likelihood ratio test for differences in models
lr_dp <- lrtest(model_full, model_natural)
lr_natural <- lrtest(model_full, model_dp)
print("Likelihood ratio of full model without DP as predictor:")
print(summary(lr_dp))

print("Likelihood ratio of full model without natural as predictor")
print(summary(lr_natural))
```