# modals specific parameters
num_forces: 2
force_names:
  - weak
  - strong
num_flavors: 3
flavor_names:
  - epistemic
  - deontic
  - circumstantial

# measures
utility: indicator # half_credit or indicator
agent_type: pragmatic # literal or pragmatic
language_of_thought:
  negation: True
universal_property: sav # iff or sav

# other experiment parameters
processes: 6
random_seed: 42
sample_size: 200
lang_size: 6
evolutionary_alg:
  generation_size: 200
  num_generations: 20
  max_mutations: 5
  num_processes: 6
  maximum_lang_size: 6
  explore: 0.0

# outputs etc
file_paths:
  meaning_space: outputs/dev/meaning_space.yml
  expressions: outputs/dev/expressions.yml
  data:
    gitksan: data/natural_languages/Gitksan/modals.csv
    javanese: data/natural_languages/Javanese-Paciran/modals.csv
    lillooet: data/natural_languages/Lillooet-Salish/modals.csv
    logoori: data/natural_languages/Logoori/modals.csv
    tlingit: data/natural_languages/Tlingit/modals.csv
  artificial_languages: outputs/dev/languages/artificial.yml
  natural_languages: outputs/dev/languages/natural.yml
  dominant_languages: outputs/dev/languages/dominant.yml # Pareto
  analysis:
    correlations: outputs/dev/analysis/correlations/property.csv # dummy property name
    data: outputs/dev/analysis/all_data.csv
    pareto_data: outputs/dev/analysis/pareto_data.csv
    plot: outputs/dev/analysis/plot.png
    means: outputs/dev/analysis/means.csv
    ttest_natural: outputs/dev/analysis/ttest_natural.csv
    ttest_dlsav: outputs/dev/analysis/ttest_dlsav.csv

# How to interpret the modal database can_express values as booleans
can_express:
  True:
    - 1
  False:
    - "?" # the '?' must be enclosed in quotes
    - 0
