# modals specific parameters
num_forces: 3
force_names:
  - weak
  - strong
  - mid
num_flavors: 3
flavor_names:
  - epistemic
  - deontic
  - circumstantial

# measures
utility: half_credit # half_credit or indicator
agent_type: pragmatic # literal or pragmatic
language_of_thought:
  negation: True

# other experiment parameters
processes: 6
random_seed: 42
sample_size: 2000
lang_size: 6
evolutionary_alg:
  generation_size: 200
  num_generations: 20
  max_mutations: 5
  num_processes: 6
  maximum_lang_size: 6

# outputs etc
file_paths:
  meaning_space: outputs/dev_3_3/meaning_space.yml
  expressions: outputs/dev_3_3/expressions.yml
  data:
    gitksan: data/natural_languages/Gitksan/modals.csv
    javanese: data/natural_languages/Javanese-Paciran/modals.csv
    lillooet: data/natural_languages/Lillooet-Salish/modals.csv
    logoori: data/natural_languages/Logoori/modals.csv
    tlingit: data/natural_languages/Tlingit/modals.csv
  artificial_languages: outputs/dev_3_3/languages/artificial.yml
  natural_languages: outputs/dev_3_3/languages/natural.yml
  dominant_languages: outputs/dev_3_3/languages/dominant.yml # Pareto
  dataframe: outputs/dev_3_3/dataframe.csv
  plot: outputs/dev_3_3/plot.png

# How to interpret the modal database can_express values as booleans
can_express:
  True:
    - 1
  False:
    - "?" # the '?' must be enclosed in quotes
    - 0
