# modals specific parameters
num_forces: 2
force_names:
  - weak
  - strong
num_flavors: 3
flavor_names:
  - epistemic
  - deontic
  - circumstantial

# measures
utility: half_credit # half_credit or indicator
agent_type: pragmatic # literal or pragmatic
language_of_thought:
  negation: True
universal_property: sav # sav or iff  

# other experiment parameters
processes: 6
random_seed: 42
sample_size: 40000
lang_size: 10
evolutionary_alg:
  generation_size: 2000
  num_generations: 200
  max_mutations: 5
  num_processes: 6
  maximum_lang_size: 10
  explore: 0

# outputs etc
file_paths:
  meaning_space: outputs/half_credit_pragmatic/meaning_space.yml
  expressions: outputs/half_credit_pragmatic/expressions.yml
  artificial_languages: outputs/half_credit_pragmatic/languages/artificial.yml
  dominant_languages: outputs/half_credit_pragmatic/languages/dominant.yml # Pareto
  analysis:
    correlations: outputs/half_credit_pragmatic/analysis/correlations/property.csv # dummy property name
    data: outputs/half_credit_pragmatic/analysis/all_data.csv
    pareto_data: outputs/half_credit_pragmatic/analysis/pareto_data.csv
    plot: outputs/half_credit_pragmatic/analysis/plot.png
    means: outputs/half_credit_pragmatic/analysis/means.csv
    ttest_dlsav: outputs/half_credit_pragmatic/analysis/ttest_dlsav.csv

# How to interpret the modal database can_express values as booleans
can_express:
  True:
    - 1
  False:
    - "?" # the '?' must be enclosed in quotes
    - 0
