# modals specific parameters
num_forces: 2
force_names:
  - weak
  - strong
num_flavors: 3
flavor_names:
  - epistemic
  - deontic
  - circumstantial

# measures
utility: half_credit # half_credit or indicator
agent_type: pragmatic # literal or pragmatic
language_of_thought:
  negation: True

# other experiment parameters
processes: 6
random_seed: 42
sample_size: 2000
lang_size: 10
evolutionary_alg:
  generation_size: 2000
  num_generations: 200
  max_mutations: 5
  num_processes: 6
  maximum_lang_size: 10

# outputs etc
file_paths:
  meaning_space: outputs/half_credit_pragmatic/meaning_space.yml
  expressions: outputs/half_credit_pragmatic/expressions.yml
  data:
    gitksan: data/natural_languages/Gitksan/modals.csv
    javanese: data/natural_languages/Javanese-Paciran/modals.csv
    lillooet: data/natural_languages/Lillooet-Salish/modals.csv
    logoori: data/natural_languages/Logoori/modals.csv
    tlingit: data/natural_languages/Tlingit/modals.csv
  artificial_languages: outputs/half_credit_pragmatic/languages/artificial.yml
  natural_languages: outputs/half_credit_pragmatic/languages/natural.yml
  dominant_languages: outputs/half_credit_pragmatic/languages/dominant.yml # Pareto
  analysis:
    correlations: outputs/half_credit_pragmatic/analysis/correlations/property.csv # dummy property name
    dataframe: outputs/half_credit_pragmatic/analysis/dataframe.csv
    plot: outputs/half_credit_pragmatic/analysis/plot.png
    means: outputs/half_credit_pragmatic/analysis/means.csv
    ttest: outputs/half_credit_pragmatic/analysis/ttest.csv

# How to interpret the modal database can_express values as booleans
can_express:
  True:
    - 1
  False:
    - "?" # the '?' must be enclosed in quotes
    - 0
