# modals specific parameters
num_forces: 2
force_names:
  - weak
  - strong
num_flavors: 3
flavor_names:
  - epistemic
  - deontic
  - circumstantial

utility_function: 'half-credit'
language_of_thought:
  - negation: True

# other experiment parameters
random_seed: 1
sample_size: 2000
lang_size: 10
evolutionary_alg:
  generation_size: 200
  num_generations: 200
  max_mutations: 5
  num_processes: 6
  maximum_lang_size: 10

# outputs etc
file_paths:
  meaning_space: outputs/main_results/meaning_space.yml
  expressions: outputs/main_results/expressions.yml
  data:
    gitksan: data/natural_languages/Gitksan/modals.csv
    javanese: data/natural_languages/Javanese-Paciran/modals.csv
    lillooet: data/natural_languages/Lillooet-Salish/modals.csv
    logoori: data/natural_languages/Logoori/modals.csv
    tlingit: data/natural_languages/Tlingit/modals.csv
  artificial_languages: outputs/main_results/languages/artificial.yml
  natural_languages: outputs/main_results/languages/natural.yml
  dominant_languages: outputs/main_results/languages/dominant.yml # Pareto
  dataframe: outputs/main_results/dataframe.csv
  plot: outputs/main_results/plot.png

# How to interpret the modal database can_express values as booleans
can_express:
  True:
    - 1
  False:
    - "?"
    - 0