# modals specific parameters
num_forces: 2
force_names:
  - weak
  - strong
num_flavors: 3
flavor_names:
  - epistemic
  - deontic
  - circumstantial
utility_function: 'half-credit'
language_of_thought:
  - negation: True

# other experiment parameters
random_seed: 1
sample_size: 2000
lang_size: 6
evolutionary_alg:
  generation_size: 200
  num_generations: 200
  max_mutations: 5
  num_processes: 6
  maximum_lang_size: 6