# modals specific parameters
num_forces: 2
force_names:
  - weak
  - strong
num_flavors: 3
flavor_names:
  - epistemic
  - deontic
  - circumstantial
utility_function: 'half-credit'
language_of_thought_operators:
  - conjunction
  - disjunction
  - negation

# other experiment parameters
sample_size: 200
maximum_language_size: 5 
evolutionary_alg:
  - seed_population_size: 200
  - num_generations: 20
  - max_mutations: 3
  - processes: 6
